#ifndef REDSHIFT_LIBK_DETAIL_CHAR_TABLE_HPP
#define REDSHIFT_LIBK_DETAIL_CHAR_TABLE_HPP

namespace detail {
    static const int char_table[] = {
        /*   0  NUL    */ int(char_class::cntrl),
        /*   1  SOH    */ int(char_class::cntrl),
        /*   2  STX    */ int(char_class::cntrl),
        /*   3  ETX    */ int(char_class::cntrl),
        /*   4  EOT    */ int(char_class::cntrl),
        /*   5  ENQ    */ int(char_class::cntrl),
        /*   6  ACK    */ int(char_class::cntrl),
        /*   7  BEL    */ int(char_class::cntrl),
        /*   8  BS     */ int(char_class::cntrl),
        /*   9  TAB    */ int(char_class::cntrl) | int(char_class::space),
        /*  10  LF     */ int(char_class::cntrl) | int(char_class::space),
        /*  11  VT     */ int(char_class::cntrl) | int(char_class::space),
        /*  12  FF     */ int(char_class::cntrl) | int(char_class::space),
        /*  13  CR     */ int(char_class::cntrl) | int(char_class::space),
        /*  14  SO     */ int(char_class::cntrl) | int(char_class::space),
        /*  15  SI     */ int(char_class::cntrl),
        /*  16  DLE    */ int(char_class::cntrl),
        /*  17  DC1    */ int(char_class::cntrl),
        /*  18  DC2    */ int(char_class::cntrl),
        /*  19  DC3    */ int(char_class::cntrl),
        /*  20  DC4    */ int(char_class::cntrl),
        /*  21  NAK    */ int(char_class::cntrl),
        /*  22  SYN    */ int(char_class::cntrl),
        /*  23  ETB    */ int(char_class::cntrl),
        /*  24  CAN    */ int(char_class::cntrl),
        /*  25  EM     */ int(char_class::cntrl),
        /*  26  SUB    */ int(char_class::cntrl),
        /*  27  ESC    */ int(char_class::cntrl),
        /*  28  FS     */ int(char_class::cntrl),
        /*  29  GS     */ int(char_class::cntrl),
        /*  30  RS     */ int(char_class::cntrl),
        /*  31  US     */ int(char_class::cntrl),
        /*  32  Space  */ int(char_class::space) | int(char_class::print),
        /*  33  !      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  34  "      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  35  #      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  36  $      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  37  %      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  38  &      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  39  '      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  40  (      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  41  )      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  42  *      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  43  +      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  44  ,      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  45  -      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  46  .      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  47  /      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  48  0      */ int(char_class::digit) | int(char_class::xdigit) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  49  1      */ int(char_class::digit) | int(char_class::xdigit) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  50  2      */ int(char_class::digit) | int(char_class::xdigit) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  51  3      */ int(char_class::digit) | int(char_class::xdigit) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  52  4      */ int(char_class::digit) | int(char_class::xdigit) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  53  5      */ int(char_class::digit) | int(char_class::xdigit) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  54  6      */ int(char_class::digit) | int(char_class::xdigit) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  55  7      */ int(char_class::digit) | int(char_class::xdigit) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  56  8      */ int(char_class::digit) | int(char_class::xdigit) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  57  9      */ int(char_class::digit) | int(char_class::xdigit) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  58  :      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  59  ;      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  60  <      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  61  =      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  62  >      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  63  ?      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  64  @      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  65  A      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print) | int(char_class::xdigit),
        /*  66  B      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print) | int(char_class::xdigit),
        /*  67  C      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print) | int(char_class::xdigit),
        /*  68  D      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print) | int(char_class::xdigit),
        /*  69  E      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print) | int(char_class::xdigit),
        /*  70  F      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print) | int(char_class::xdigit),
        /*  71  G      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  72  H      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  73  I      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  74  J      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  75  K      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  76  L      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  77  M      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  78  N      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  79  O      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  80  P      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  81  Q      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  82  R      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  83  S      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  84  T      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  85  U      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  86  V      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  87  W      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  88  X      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  89  Y      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  90  Z      */ int(char_class::upper) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /*  91  [      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  92  \      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  93  ]      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  94  ^      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  95  _      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  96  `      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /*  97  a      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print) | int(char_class::xdigit),
        /*  98  b      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print) | int(char_class::xdigit),
        /*  99  c      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print) | int(char_class::xdigit),
        /* 100  d      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print) | int(char_class::xdigit),
        /* 101  e      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print) | int(char_class::xdigit),
        /* 102  f      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print) | int(char_class::xdigit),
        /* 103  g      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /* 104  h      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /* 105  i      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /* 106  j      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /* 107  k      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /* 108  l      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /* 109  m      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /* 110  n      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /* 111  o      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /* 112  p      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /* 113  q      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /* 114  r      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /* 115  s      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /* 116  t      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /* 117  u      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /* 118  v      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /* 119  w      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /* 120  x      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /* 121  y      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /* 122  z      */ int(char_class::lower) | int(char_class::alpha) | int(char_class::alnum) | int(char_class::graph) | int(char_class::print),
        /* 123  {      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /* 124  |      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /* 125  }      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /* 126  ~      */ int(char_class::punct) | int(char_class::graph) | int(char_class::print),
        /* 127  DEL    */ int(char_class::cntrl)
    };
} // detail

#endif // ! REDSHIFT_LIBK_DETAIL_CHAR_TABLE_HPP
