#!/bin/bash

# Generates initial ramdisks.

set -e

script=$(basename "$0")
here=$(dirname "$0")
bin="$(pwd)/$here/mkinitrd-bin"
file="$(pwd)/$1"
path="$2"

function get_files
{
    echo "$file"
    for input in $(find . -type f); do
        echo "$input" | sed 's/^.//'
    done
}

if [[ $# -ne 2 || ! -d "$path" ]]; then
    cat >&2 <<EOF
Usage: $0 <file> <path>
where <file> is the output file to generate.
  and <path> is the path to a directory containing input files.
EOF
fi

pushd "$path"
get_files | xargs "$bin"
popd
